### ISSUE TITLE
Sports Pages

### ISSUE THREAD

**Issue by CheeseFry** [BWheatie/Better-Than-Most#16]
New page format, 
Grids for new pages

**Comment by BWheatie** [comment]
Looks good. Lets add this same grid to the front page and authors. Add all of the sports to the grids and find some consistent pictures to use as backgrounds. Want something simple for those. No need to complicate it.

**Comment by BWheatie** [comment]
Hold. that thought on the homepage. I might want to do something else there.

**Comment by CheeseFry** [comment]
How about we close this and start a new issue with clear goals?
