### ISSUE TITLE
Organize articles by sport and author

### ISSUE THREAD

**Issue by kurtisnelson** [BWheatie/Better-Than-Most#4]
Users should be able to view articles by author or by sport

* NFL
* MLB
* NBA
* NHL

**Comment by CheeseFry** [comment]
@BWheatie 
Do you want a dividing line anywhere? or a list without breaks?
<img width="224" alt="screen shot 2015-07-14 at 11 35 29 am" src="https://cloud.githubusercontent.com/assets/11729686/8678825/7f1dcf34-2a1c-11e5-8d63-69e64ff31186.png">

**Comment by BWheatie** [comment]
Split at opinions.

**Comment by BWheatie** [comment]
Can we also create a nice grid layout on the individual sport pages? Leave it empty for now or dummy info. It will fill in later with teams, leagues.

**Comment by CheeseFry** [comment]
@BWheatie  
Do you want EACH item in the dropdown list to open to a unique page with grid format? 
If yes, the grid should be how many columns? rows?

**Comment by BWheatie** [comment]
Yes. Size doesn't matter right now.

**Comment by BWheatie** [comment]
Yes. Each item loads to a unique site. Likely the data will push to the site by way of a tag.
Ill build out the exact size of the grid later because it will change per sport.
