### ISSUE TITLE
Social Media Buttons

### ISSUE THREAD

**Issue by BWheatie** [BWheatie/Better-Than-Most#7]
Add social media buttons to homepage.

**Comment by LukeSettle** [comment]
Do you want the social media buttons to be links to that social media site. Or do you want them to have other functionality, such as being able to tweet from our page?

**Comment by BWheatie** [comment]
Just the ability to go to the sites social media site. Or the ability to follow the feeds from the site.

**Comment by LukeSettle** [comment]
What is the twitter account that you want people to follow?

**Comment by LukeSettle** [comment]
Do we have a facebook account?

**Comment by BWheatie** [comment]
@wearebtms

**Comment by BWheatie** [comment]
Lets get rid of the follow wearebtms on the article page and "Like". If we could integrate all the shares in 1 dropdown button I think that would be better.

**Comment by BWheatie** [comment]
Redesign social media buttons to match site theme. Universal share button with media drop down.
