### ISSUE TITLE
Add to Nav bar

### ISSUE THREAD

**Issue by BWheatie** [BWheatie/Better-Than-Most#8]
Sports
-NFL
-MLB
-NBA
-NHL
-Golf
-Soccer
-Outdoors
-Action
-Opinions

Authors(per Author)
-Bio
-Articles Authored

-About
-Contact

**Comment by CheeseFry** [comment]
@BWheatie 
Check recent push. Is this enough to close #8?

**Comment by BWheatie** [comment]
Looks great.
